Abordo/Controllers/CadastrarController.cs
using Abordo.Models;
using Abordo.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Abordo.Controllers
{
    //rota
    [Route("Cadastrars")]
    public class CadastrarController : Controller
    {
        //vai listar todos clientes cadastrados
        [HttpGet]
        [Route("Listar")]
        public IActionResult Index()
        {
            var dbContext = new Contexto();
            //vai receber dados com o obj ViewData do bd
            ViewData["Cadastrars"] = dbContext.Cadastrars.Where(p => p.IdCli > 0).ToList();
            return View();
        }
        public IActionResult Cad()
        {
            return View();
        }

        [HttpPost]
        [Route("Listar")]
        public IActionResult Index(Cadastrar cadastrar)
        {
            var dbContext = new Contexto();
            dbContext.Add(cadastrar);

            //salvar no bd
            dbContext.SaveChanges();

            return RedirectToAction("Index");
            //  return View();
            // return View("Index");
        }
        //excluir
        [HttpPost]
        public IActionResult Deletar(Cadastrar cadastrar)
        {
            var dbcontext = new Contexto();

            var cadastrarDelete = dbcontext.Cadastrars.Find(cadastrar.IdCli);
            dbcontext.Remove(cadastrarDelete);
            dbcontext.SaveChanges();

            return RedirectToAction("Index");
        }
        public IActionResult Atualizar(Cadastrar novosDadosCadastrar)
        {
            var dbcontext = new Contexto();

            var antigosDadosCadastrar= dbcontext.Cadastrars.Find(novosDadosCadastrar.IdCli);

            antigosDadosCadastrar.NomeCli = novosDadosCadastrar.NomeCli;
            antigosDadosCadastrar.CPFCli = novosDadosCadastrar.CPFCli;
            antigosDadosCadastrar.NasCli = novosDadosCadastrar.NasCli;
            antigosDadosCadastrar.CEPCli = novosDadosCadastrar.CEPCli;
            antigosDadosCadastrar.BairroCli = novosDadosCadastrar.BairroCli;
            antigosDadosCadastrar.EnderecoCli = novosDadosCadastrar.EnderecoCli;
            antigosDadosCadastrar.NumeroCli = novosDadosCadastrar.NumeroCli;
            antigosDadosCadastrar.TelefoneCli = novosDadosCadastrar.TelefoneCli;
            antigosDadosCadastrar.EmailCli = novosDadosCadastrar.EmailCli;
            antigosDadosCadastrar.Situacao = novosDadosCadastrar.Situacao;



            dbcontext.SaveChanges();

            return RedirectToAction("Index");
        }
    }
   
    }

Abordo/Controllers/ContatoController.cs
using Abordo.Data;
using Abordo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Abordo.Controllers
{

    //rota
    [Route("Contatos")]
    public class ContatoController : Controller
    {
        //vai listar todos clientes cadastrados
        [HttpGet]
        [Route("Listar")]
        public IActionResult Index()
        {
            var dbContext = new Contexto();
            //vai receber dados com o obj ViewData do bd
            ViewData["Contatos"] = dbContext.Contatos.Where(p => p.IdContato > 0).ToList();
            return View();
        }

        [HttpPost]
        [Route("Listar")]
        public IActionResult Index(Contato contato)
        {
            var dbContext = new Contexto();
            dbContext.Add(contato);

            //salvar no bd
            dbContext.SaveChanges();

            return RedirectToAction("Index");
            //  return View();
            // return View("Index");
        }
        //excluir
        [HttpPost]
        public IActionResult Deletar(Contato contato)
        {
            var dbcontext = new Contexto();

            var contatoDelete = dbcontext.Destinos.Find(contato.IdContato);
            dbcontext.Remove(contatoDelete);
            dbcontext.SaveChanges();

            return RedirectToAction("Index");
        }
        public IActionResult Atualizar(Contato novosDadosContato)
        {
            var dbcontext = new Contexto();

            var antigosDadosContato = dbcontext.Contatos.Find(novosDadosContato.IdContato);

            antigosDadosContato.NomeContato = novosDadosContato.NomeContato;
            antigosDadosContato.EmailContato = novosDadosContato.EmailContato;
            antigosDadosContato.MsgContato = novosDadosContato.MsgContato;
            

            dbcontext.SaveChanges();

            return RedirectToAction("Index");
        }
    }

}

Abordo/Controllers/DestinoController.cs
using Abordo.Data;
using Abordo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Abordo.Controllers
{
    //rota
    [Route("Destinos")]
    public class DestinoController : Controller
    {
        private object novosDadosDestinos;

        //vai listar todos clientes cadastrados
        [HttpGet]
        [Route("Listar")]
        public IActionResult Index()
        {
            var dbContext = new Contexto();
            //vai receber dados com o obj ViewData do bd
            ViewData["Destinos"] = dbContext.Destinos.Where(p => p.IdDestino > 0).ToList();
            return View();
        }

        [HttpPost]
        [Route("Listar")]
        public IActionResult Index(Destino destino)
        {
            var dbContext = new Contexto();
            dbContext.Add(destino);

            //salvar no bd
            dbContext.SaveChanges();

            return RedirectToAction("Index");
            //  return View();
            // return View("Index");
        }

        //excluir
        [HttpPost]
        public IActionResult Deletar(Destino destino)
        {
            var dbcontext = new Contexto();

            var destinoDelete = dbcontext.Destinos.Find(destino.IdDestino);
            dbcontext.Remove(destinoDelete);
            dbcontext.SaveChanges();

            return RedirectToAction("Index");
        }   
        public IActionResult Atualizar(Destino novosDadosDestino)
        {
            var dbcontext = new Contexto();

            var antigosDadosDestino = dbcontext.Destinos.Find(novosDadosDestino.IdDestino);

            antigosDadosDestino.CPFCli = novosDadosDestino.CPFCli;
            antigosDadosDestino.PartidaDestino = novosDadosDestino.PartidaDestino;
            antigosDadosDestino.NomeDestino = novosDadosDestino.NomeDestino;
            antigosDadosDestino.HoraDestino = novosDadosDestino.HoraDestino;
            antigosDadosDestino.DataDestina = novosDadosDestino.DataDestina;

            dbcontext.SaveChanges();

            return RedirectToAction("Index");
        }
        

    }
}

Abordo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Abordo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar fixed-top navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow mb-3" >
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Abordo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon" style="color:aliceblue; background-color:aliceblue"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="Index">Contato</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Destino" asp-action="Index">Destino</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cadastrar" asp-action="Index">Cadastrar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Desconto">desconto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color:#000000">

        <div class="container" style="color: #ef8141; text-align:center ">

            &copy;todosdireitosreservadosparaa-bordo 2021 - Abordo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>